#!/usr/bin/env python3
"""
Bump versi aplikasi dengan format yy.m.d.seri.

- yy  : 2 digit tahun (mis. 26 untuk 2026)
- m   : bulan tanpa leading zero (1-12)
- d   : tanggal tanpa leading zero (1-31)
- seri: increment tiap build di tanggal yang sama; reset ke 0 kalau tanggal ganti

State disimpan di version.json:
    {"yy": 26, "m": 6, "d": 23, "seri": 3, "version": "26.6.23.3"}

File yang di-generate:
    _version.py         -> APP_VERSION string, untuk di-import main.py
    version_info.txt    -> versi string sederhana, untuk version_file PyInstaller

Pemakaian:
    python bump_version.py            # bump +1
    python bump_version.py --show     # tampilkan versi saat ini tanpa bump
    python bump_version.py --set 26.6.23.5   # set eksplisit
"""

import json
import sys
import argparse
from datetime import datetime
from pathlib import Path

REPO_DIR = Path(__file__).resolve().parent
STATE_FILE = REPO_DIR / "version.json"
VERSION_PY = REPO_DIR / "webview2-app" / "_version.py"
VERSION_TXT = REPO_DIR / "version_info.txt"


def _today_parts():
    now = datetime.now()
    return now.year % 100, now.month, now.day


def _load_state():
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _save_state(state):
    STATE_FILE.write_text(
        json.dumps(state, indent=2) + "\n", encoding="utf-8"
    )


def _write_generated_files(version, state):
    """Tulis _version.py dan version_info.txt."""
    VERSION_PY.write_text(
        f'"""Auto-generated by bump_version.py. Jangan edit manual."""\n'
        f'APP_VERSION = "{version}"\n',
        encoding="utf-8",
    )
    VERSION_TXT.write_text(version + "\n", encoding="utf-8")


def _format_version(yy, m, d, seri):
    return f"{yy}.{m}.{d}.{seri}"


def _parse_version_string(s):
    parts = s.strip().split(".")
    if len(parts) != 4:
        raise ValueError(f"Format versi harus yy.m.d.seri, dapat: {s!r}")
    yy, m, d, seri = (int(p) for p in parts)
    return yy, m, d, seri


def bump():
    state = _load_state()
    yy, m, d = _today_parts()

    prev_yy = state.get("yy")
    prev_m = state.get("m")
    prev_d = state.get("d")
    prev_seri = state.get("seri", -1)

    if prev_yy == yy and prev_m == m and prev_d == d:
        seri = prev_seri + 1
    else:
        seri = 0

    version = _format_version(yy, m, d, seri)
    new_state = {
        "yy": yy,
        "m": m,
        "d": d,
        "seri": seri,
        "version": version,
    }
    _save_state(new_state)
    _write_generated_files(version, new_state)
    print(f"[bump] version: {version}")
    return version


def set_explicit(version_str):
    yy, m, d, seri = _parse_version_string(version_str)
    version = _format_version(yy, m, d, seri)
    state = {
        "yy": yy,
        "m": m,
        "d": d,
        "seri": seri,
        "version": version,
    }
    _save_state(state)
    _write_generated_files(version, state)
    print(f"[set] version: {version}")
    return version


def show():
    state = _load_state()
    version = state.get("version", "(belum ada)")
    print(f"[show] version: {version}")
    return version


def get_version():
    """Ambil versi saat ini sebagai string (dipakai oleh main.py tanpa bump)."""
    return _load_state().get("version", "0.0.0.0")


def main():
    parser = argparse.ArgumentParser(
        description="Bump versi aplikasi format yy.m.d.seri"
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Tampilkan versi saat ini tanpa bump",
    )
    parser.add_argument(
        "--set",
        metavar="VERSION",
        help="Set versi eksplisit, mis. --set 26.6.23.5",
    )
    args = parser.parse_args()

    if args.show:
        show()
        return
    if args.set:
        set_explicit(args.set)
        return
    bump()


if __name__ == "__main__":
    main()